name: Django CI - Testing

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  run_django_tests: 

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: smp_db
        ports:
        - 5433:5433

    steps:
    - uses: actions/checkout@v3 

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install PostgreSQL Dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install postgresql-client postgresql-server-dev-all

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create test database
      run: createdb smp_db -U postgres -h localhost -p 5433

    - name: Run migrations
      run: python manage.py migrate --database=smp_db

    - name: Run tests
      run: python manage.py test --database=smp_db

    - name: Run Tests
      run: |
        python ./SmartMarketPlace_backend/manage.py test core

    - name: Drop test database
      run: dropdb smp_db -U postgres -h localhost -p 5433
