name: TEST - running django tests 
on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  push_to_test2_backend:
    runs-on: ubuntu-latest
    steps:
    # Se hace este checkout para que podamos encontrar los archivos que tenemos en develop
    - name: Checkout
      uses: actions/checkout@v3

    - name: Testing Django API
      uses: python ./SmartMarketPlace_backend/manage.py test core
    
    
