name: Django CI - Testing

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  run_django_tests: 

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: smp_db
        ports:
        - 5433:5432

    steps:
    - uses: actions/checkout@v3 

    - name: Install PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib
        sudo systemctl start postgresql
        sudo systemctl enable postgresql

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create test database
      run: |
        sudo su postgres -c "createdb smp_db"
        sudo su postgres -c "psql -c 'create extension if not exists hstore;' smp_db"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run migrations
      run: |
      python ./SmartMarketPlace_backend/manage.py makemigrations --database=smp_db
      python ./SmartMarketPlace_backend/manage.py migrate --database=smp_db

    - name: Run tests
      run: python ./SmartMarketPlace_backend/manage.py test --database=smp_db

    - name: Run Tests
      run: |
        python ./SmartMarketPlace_backend/manage.py test core

    - name: Drop test database
      run: sudo su postgres -c "dropdb smp_db"
