name: TEST - backend to frontend Workflow

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

permissions: write-all

jobs: 
  push_to_test2_backend:
    runs-on: ubuntu-latest
    steps:
    # Se hace este checkout para que podamos encontrar los archivos que tenemos en develop
    - name: Checkout
      uses: actions/checkout@v3

    - name: Git set repo url
      run: git remote set-url origin git@github.com:Daga2001/SmartMarketPlace.git

    - name: Configurar credenciales de SSH
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-add -D
        ssh-add ~/.ssh/id_rsa

    - name: Fetching remote branches
      run: git fetch

    - name: Git checkout test2
      run: git checkout -b test2 origin/test2

    - name: Git config username
      run: git config --global user.email '${{secrets.GIT_EMAIL}}'

    - name: Git config password
      run: git config --global user.name '${{secrets.GIT_NAME}}'

    - name: Git merge with develop
      run: git merge --strategy-option=theirs --allow-unrelated-histories test

    - name: Debug 
      run: |
        echo "Current directory: $(pwd)"
        echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
        echo "List of files: $(ls)"
        echo "Git remote -v: $(git remote -v)"
        echo "Git config user: $(git config user.name), $(git config user.email)"

    - name: Git push 
      run: git push origin HEAD:refs/heads/test2 --force-with-lease
      env:
        FRONT_TOKEN: ${{ secrets.FRONT_TOKEN }}