name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install XVFB
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Launch XVFB
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x16 > /dev/null 2>&1 &
        sleep 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-django
        wget https://chromedriver.storage.googleapis.com/94.0.4606.41/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Run migrations
      run: python ./SmartMarketPlace_backend/manage.py migrate

    - name: Run core app
      run: python ./SmartMarketPlace_backend/manage.py runserver &

    - name: Run tests
      run: pytest --driver-path=$CHROMEDRIVER_PATH ./SmartMarketPlace_backend/manage.py test core
      env:
        CHROMEDRIVER_PATH: ./SmartMarketPlace_backend/core/drivers/chromedriver_linux64.zip